version: '3.1'

services:

  psql:
    container_name: pgsql 
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: my_db
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
volumes:
  database-data:
